# GLOBAL VARIABLES
DATASET = {'AFGHANISTAN': 'af', 'ALBANIA': 'al', 'ALGERIA': 'dz', 'AMERICAN SAMOA': 'as', 'ANDORRA': 'ad',
           'ANGOLA': 'ao', 'ANGUILLA': 'ai', 'ANTARCTICA': 'aq', 'ANTIGUA AND BARBUDA': 'ag',
           'ARGENTINA': 'ar', 'ARMENIA': 'am', 'ARUBA': 'aw', 'AUSTRALIA': 'au', 'AUSTRIA': 'at',
           'AZERBAIJAN': 'az', 'BAHAMAS': 'bs', 'BAHRAIN': 'bh', 'BANGLADESH': 'bd', 'BARBADOS': 'bb',
           'BELARUS': 'by', 'BELGIUM': 'be', 'BELIZE': 'bz', 'BENIN': 'bj', 'BERMUDA': 'bm',
           'BHUTAN': 'bt', 'BOLIVIA': 'bo', 'BOSNIA AND HERZEGOVINA': 'ba', 'BOTSWANA': 'bw',
           'BOUVET ISLAND': 'bv', 'BRAZIL': 'br', 'BRITISH INDIAN OCEAN TERRITORY': 'io',
           'BRUNEI DARUSSALAM': 'bn', 'BULGARIA': 'bg', 'BURKINA FASO': 'bf', 'BURUNDI': 'bi',
           'CAMBODIA': 'kh', 'CAMEROON': 'cm', 'CANADA': 'ca', 'CAPE VERDE': 'cv',
           'CAYMAN ISLANDS': 'ky', 'CENTRAL AFRICAN REPUBLIC': 'cf', 'CHAD': 'td', 'CHILE': 'cl',
           'CHINA': 'cn', 'CHRISTMAS ISLAND': 'cx', 'COCOS (KEELING) ISLANDS': 'cc', 'COLOMBIA': 'co',
           'COMOROS': 'km', 'CONGO': 'cg', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE': 'cd',
           'COOK ISLANDS': 'ck', 'COSTA RICA': 'cr', "COTE D'IVOIRE": 'ci', 'CROATIA': 'hr',
           'CUBA': 'cu', 'CYPRUS': 'cy', 'CZECH REPUBLIC': 'cz', 'DENMARK': 'dk', 'DJIBOUTI': 'dj',
           'DOMINICA': 'dm', 'DOMINICAN REPUBLIC': 'do', 'ECUADOR': 'ec', 'EGYPT': 'eg',
           'EL SALVADOR': 'sv', 'EQUATORIAL GUINEA': 'gq', 'ERITREA': 'er', 'ESTONIA': 'ee',
           'ETHIOPIA': 'et', 'FALKLAND ISLANDS (MALVINAS)': 'fk', 'FAROE ISLANDS': 'fo',
           'FIJI': 'fj', 'FINLAND': 'fi', 'FRANCE': 'fr', 'FRENCH GUIANA': 'gf',
           'FRENCH POLYNESIA': 'pf', 'FRENCH SOUTHERN TERRITORIES': 'tf', 'GABON': 'ga',
           'GAMBIA': 'gm', 'GEORGIA': 'ge', 'GERMANY': 'de', 'GHANA': 'gh', 'GIBRALTAR': 'gi',
           'GREECE': 'gr', 'GREENLAND': 'gl', 'GRENADA': 'gd', 'GUADELOUPE': 'gp', 'GUAM': 'gu',
           'GUATEMALA': 'gt', 'GUINEA': 'gn', 'GUINEA-BISSAU': 'gw', 'GUYANA': 'gy', 'HAITI': 'ht',
           'HEARD ISLAND AND MCDONALD ISLANDS': 'hm', 'HOLY SEE (VATICAN CITY STATE)': 'va',
           'HONDURAS': 'hn', 'HONG KONG': 'hk', 'HUNGARY': 'hu', 'ICELAND': 'is', 'INDIA': 'in',
           'INDONESIA': 'id', 'IRAN, ISLAMIC REPUBLIC OF': 'ir', 'IRAQ': 'iq', 'IRELAND': 'ie',
           'ISRAEL': 'il', 'ITALY': 'it', 'JAMAICA': 'jm', 'JAPAN': 'jp', 'JORDAN': 'jo',
           'KAZAKHSTAN': 'kz', 'KENYA': 'ke', 'KIRIBATI': 'ki',
           "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF": 'kp', 'KOREA, REPUBLIC OF': 'kr', 'KUWAIT': 'kw',
           'KYRGYZSTAN': 'kg', "LAO PEOPLE'S DEMOCRATIC REPUBLIC": 'la', 'LATVIA': 'lv',
           'LEBANON': 'lb', 'LESOTHO': 'ls', 'LIBERIA': 'lr', 'LIBYAN ARAB JAMAHIRIYA': 'ly',
           'LIECHTENSTEIN': 'li', 'LITHUANIA': 'lt',
           'LUXEMBOURG': 'lu', 'MACAO': 'mo',
           'MACEDONIA, THE FORMER YUGOSALV REPUBLIC OF': 'mk',
           'MADAGASCAR': 'mg', 'MALAWI': 'mw', 'MALAYSIA': 'my',
           'MALDIVES': 'mv', 'MALI': 'ml', 'MALTA': 'mt', 'MARSHALL ISLANDS': 'mh',
           'MARTINIQUE': 'mq', 'MAURITANIA': 'mr', 'MAURITIUS': 'mu', 'MAYOTTE': 'yt',
           'MEXICO': 'mx', 'MICRONESIA, FEDERATED STATES OF': 'fm', 'MOLDOVA, REPUBLIC OF': 'md',
           'MONACO': 'mc', 'MONGOLIA': 'mn', 'MONTSERRAT': 'ms', 'MOROCCO': 'ma', 'MOZAMBIQUE': 'mz',
           'MYANMAR': 'mm', 'NAMIBIA': 'na', 'NAURU': 'nr', 'NEPAL': 'np', 'NETHERLANDS': 'nl',
           'NETHERLANDS ANTILLES': 'an', 'NEW CALEDONIA': 'nc', 'NEW ZEALAND': 'nz', 'NICARAGUA': 'ni',
           'NIGER': 'ne', 'NIGERIA': 'ng', 'NIUE': 'nu', 'NORFOLK ISLAND': 'nf',
           'NORTHERN MARIANA ISLANDS': 'mp', 'NORWAY': 'no', 'OMAN': 'om', 'PAKISTAN': 'pk',
           'PALAU': 'pw', 'PALESTINIAN TERRITORY, OCCUPIED': 'ps', 'PANAMA': 'pa',
           'PAPUA NEW GUINEA': 'pg', 'PARAGUAY': 'py', 'PERU': 'pe', 'PHILIPPINES': 'ph',
           'PITCAIRN': 'pn', 'POLAND': 'pl', 'PORTUGAL': 'pt', 'PUERTO RICO': 'pr',
           'QATAR': 'qa', 'REUNION': 're', 'ROMANIA': 'ro', 'RUSSIAN FEDERATION': 'ru',
           'RWANDA': 'rw', 'SAINT HELENA': 'sh', 'SAINT KITTS AND NEVIS': 'kn',
           'SAINT LUCIA': 'lc', 'SAINT PIERRE AND MIQUELON': 'pm',
           'SAINT VINCENT AND THE GRENADINES': 'vc', 'SAMOA': 'ws', 'SAN MARINO': 'sm',
           'SAO TOME AND PRINCIPE': 'st', 'SAUDI ARABIA': 'sa', 'SENEGAL': 'sn',
           'SERBIA AND MONTENEGRO': 'rs', 'SEYCHELLES': 'sc', 'SIERRA LEONE': 'sl',
           'SINGAPORE': 'sg', 'SLOVAKIA': 'sk', 'SLOVENIA': 'si',
           'SOLOMON ISLANDS': 'sb', 'SOMALIA': 'so', 'SOUTH AFRICA': 'za',
           'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'gs', 'SPAIN': 'es',
           'SRI LANKA': 'lk', 'SUDAN': 'sd', 'SURINAME': 'sr', 'SVALBARD AND JAN MAYEN': 'sj',
           'SWAZILAND': 'sz', 'SWEDEN': 'se', 'SWITZERLAND': 'ch', 'SYRIAN ARAB REPUBLIC': 'sy',
           'TAIWAN, PROVINCE OF CHINA': 'tw', 'TAJIKISTAN': 'tj', 'TANZANIA, UNITED REPUBLIC OF': 'tz',
           'THAILAND': 'th', 'TIMOR-LESTE': 'tl', 'TOGO': 'tg', 'TOKELAU': 'tk', 'TONGA': 'to',
           'TRINIDAD AND TOBAGO': 'tt', 'TUNISIA': 'tn', 'TURKEY': 'tr', 'TURKMENISTAN': 'tm',
           'TURKS AND CAICOS ISLANDS': 'tc', 'TUVALU': 'tv', 'UGANDA': 'ug', 'UKRAINE': 'ua',
           'UNITED ARAB EMIRATES': 'ae', 'UNITED KINGDOM': 'gb', 'UNITED STATES': 'us',
           'UNITED STATES MINOR OUTLYING ISLANDS': 'um', 'URUGUAY': 'uy', 'UZBEKISTAN': 'uz',
           'VANUATU': 'vu', 'VENEZUELA': 've', 'VIET NAM': 'vn', 'VIRGIN ISLANDS, BRITISH': 'vg',
           'VIRGIN ISLANDS, U.S.': 'vi', 'WALLIS AND FUTUNA': 'wf', 'WESTERN SAHARA': 'eh',
           'YEMEN': 'ye', 'ZAMBIA': 'zm', 'ZIMBABWE': 'zw'}

# Functions


def geo_code(loc):
    try:
        return DATASET[loc.upper()]
    except:
        return ""
